server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/roomx?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 515155Xxx
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        connection:
          characterEncoding: utf8
          useUnicode: true
  cache:
    type: simple
    cache-names: users,rooms,applications,stats,notifications

# 定时任务配置
scheduling:
  pool-size: 10
  thread-name-prefix: "scheduled-task-"
  
# 缓存配置
cache:
  refresh-interval: 300000  # 5分钟
  cleanup-interval: 3600000 # 1小时
  stats-refresh-interval: 120000 # 2分钟

# 日志配置
logging:
  level:
    com.roomx: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 